// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"log/slog"
	"workmate/internal/api"
	"workmate/internal/config"
	"workmate/internal/domain/providers/something"
	"workmate/internal/domain/providers/task"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	repository := Task.ProvideTaskRepository()
	service := something.ProvideSomethingService()
	taskService := Task.ProvideTaskService(repository, service)
	taskHandler := Task.ProvideTaskHandler(taskService, log)
	serverHTTP := api.NewServerHTTP(cfg, taskHandler)
	return serverHTTP, nil
}
